before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
language: android
android:
  components:
  - build-tools-28.0.3
  - android-28
script:
- "./gradlew ktlint"
- "./gradlew clean build"
- "./gradlew test jacocoTestReport"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- openssl aes-256-cbc -K $encrypted_f7c7591dbff3_key -iv $encrypted_f7c7591dbff3_iv
  -in .keystore.enc -out .keystore -d
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  api_key:
    secure:
  file_glob: true
  file: "**/github/app-github-release.apk"
  on:
    tags: true
    repo: vadret/android
